modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/quek04/Food-Swords/issues" #optional
[[mods]] #mandatory
modId="food_swords" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Food Swords" #mandatory
authors="quek" #optional
description='''
Edible swords! Why? Why not.
'''
[[dependencies.food_swords]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.food_swords]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
